apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-assistant-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kubernetes-assistant-server
        version: v1
    spec:
      containers:
      - name: kubernetes-assistant-server
        image: docker.io/<DOCKERHUB_USERNAME>/kubernetes-assistant
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-assistant-server-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      name: http
  type: LoadBalancer
  selector:
    name: kubernetes-assistant-server
